config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :recipes
  resources :ingredients
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many (:recipes)
  validates :category_name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many (:recipes)
  validates :ingredient_name, presence: true
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many (:categories)
  has_and_belongs_to_many (:ingredients)
  validates :name, presence: true, uniqueness: true

  before_save(:titleize_recipe, presence: name, uniqueness: true)

  private
    def titleize_recipe
      self.name = self.name.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render :index
  end

  def new
    @category = Category.new
    render :new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category successfully added!"
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    render :edit
  end

  def show
    @category = Category.find(params[:id])
    render :show
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category successfully updated!"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    flash[:notice] = "Category has been successfully deleted"
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:category_name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
    render :index
  end

  def new
    @ingredient = Ingredient.new
    render :new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:notice] = "Ingredient successfully added!"
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    render :edit
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    render :show
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      render :edit
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id]).destroy
    redirect_to ingredients_path
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:ingredient_name)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @recipes = Recipe.all
    @categories = Category.all
    @ingredients = Ingredient.all
    render :index
  end

  def new
    @recipe = Recipe.new
    @categories = Category.all
    @ingredients = Ingredient.all
    render :new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @categories = Category.all
    @ingredients = Ingredient.all
    if @recipe.save
      if params[:category_selection].to_i != 0
        category = Category.find(params[:category_selection].to_i)
        category.recipes << @recipe
      end
      if params[:ingredient_selection].to_i != 0
        ingredient = Ingredient.find(params[:ingredient_selection].to_i)
        ingredient.recipes << @recipe
      end
      flash[:notice] = "Recipe successfully added!"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @categories = Category.all
    @ingredients = Ingredient.all
    render :edit
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = Ingredient.all
    @categories = Category.all
    render :show
  end

  def update
    @recipe = Recipe.new(recipe_params)
    @categories = Category.all
    @ingredients = Ingredient.all
    if @recipe.update(recipe_params)
      if params[:category_selection].to_i != 0
        category = Category.find(params[:category_selection].to_i)
        category.recipes << @recipe
      end
      if params[:ingredient_selection].to_i != 0
        ingredient = Ingredient.find(params[:ingredient_selection].to_i)
        ingredient.recipes << @recipe
      end
      flash[:notice] = "Recipe has been successfully updated"
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    flash[:notice] = "Recipe has been successfully deleted"
    redirect_to recipes_path
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :instructions)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render "layouts/category_form" %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if @categories.any? %>
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.category_name, category_path(category) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no categories yet.</p>
<% end %>


<p><%= link_to "Create new category", new_category_path %></p>
<p><%= link_to "Recipes", recipes_path %></p>

app/views/categories/new.html.erb
<h1>Edit category</h1>

<%= render "layouts/category_form" %>

app/views/categories/show.html.erb
<h1><%= @category.category_name %></h1>

<p><%= link_to "Edit", edit_category_path(@category) %></p>
<p><%= link_to "Delete", category_path(@category), :data =>
  {
    :confirm => "You sure?",
    :method => "delete"
  } %></p>

<p><%= link_to "Return to ingredients", ingredients_path %></p>
<p><%= link_to "Recipes", recipes_path %></p>

app/views/home/index.html.erb
<p><%= link_to "Recipes", recipes_path %></p>
<p><%= link_to "Ingredients", ingredients_path %></p>
<p><%= link_to "Categories", categories_path %></p>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= render "layouts/ingredient_form" %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<% if @ingredients.any? %>
  <ul>
    <% @ingredients.each do |ingredient| %>
      <li><%= link_to ingredient.ingredient_name, ingredient_path(ingredient) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no ingredients yet.</p>
<% end %>


<p><%= link_to "Create new ingredient", new_ingredient_path %></p>
<p><%= link_to "Recipes", recipes_path %></p>

app/views/ingredients/new.html.erb
<h1>Edit ingredient</h1>

<%= render "layouts/ingredient_form" %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.ingredient_name %></h1>

<p><%= link_to "Edit", edit_ingredient_path(@ingredient) %></p>
<p><%= link_to "Delete", ingredient_path(@ingredient), :data =>
  {
    :confirm => "You sure?",
    :method => "delete"
  } %></p>

<p><%= link_to "Return to ingredients", ingredients_path %></p>

app/views/layouts/_category_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= form_for @category do |f| %>
  <%= f.label :category_name %>
  <%= f.text_field :category_name %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Recipes", recipes_path %></p>
<p><%= link_to "Return to categories", categories_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_ingredient_form.html.erb
<%= render "layouts/errors", :object => @ingredient %>

<%= form_for @ingredient do |f| %>
  <%= f.label :ingredient_name %>
  <%= f.text_field :ingredient_name %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Recipes", recipes_path %></p>
<p><%= link_to "Return to ingredients", ingredients_path %></p>

app/views/layouts/_recipe_form.html.erb
<%= render "layouts/errors", :object => @recipe %>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :instructions %>
  <%= f.text_area :instructions %>

  <% if @categories.any? %>
    <select id="category" name="category_selection">
      <option>Select Category</option>
    <% @categories.each do |category| %>
      <option value=<%= "#{category.id}" %>><%= category.category_name %></option>
    <% end %>
    </select>
  <% else %>
    <p>There are no Categories</p>
  <% end %>

  <% if @ingredients.any? %>
    <select name="ingredient_selection">
      <option>Select Ingredient</option>
    <% @ingredients.each do |ingredient| %>
      <option value=<%= "#{ingredient.id}" %>><%= ingredient.ingredient_name %></option>
    <% end %>
    </select>
  <% else %>
    <p>There are no Ingredients</p>
  <% end %>

  <%= f.submit %>
<% end %>

<p><%= link_to "Recipes", recipes_path %></p>
<p><%= link_to "Return to ingredients", ingredients_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "layouts/recipe_form" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<% if @recipes.any? %>
  <ul>
    <% @recipes.each do |recipe| %>
      <li><%= link_to recipe.name, recipe_path(recipe) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no recipes yet.</p>
<% end %>


<p><%= link_to "Create new recipe", new_recipe_path %></p>
<p><%= link_to "Ingredients", ingredients_path %></p>
<p><%= link_to "Categories", categories_path %></p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "layouts/recipe_form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Categories</h2>
<% if @recipe.categories.any? %>
  <ul>
    <% @recipe.categories.each do |category| %>
      <li><%= link_to category.category_name, category_path(category) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no categories on this recipe yet.</p>
<% end %>

<h2>Ingredients</h2>
<% if @recipe.ingredients.any? %>
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
      <li><%= link_to ingredient.ingredient_name, ingredient_path(ingredient) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no ingredients on this recipe yet.</p>
<% end %>

<h2>Instructions</h2>

<p><%= @recipe.instructions %></p>

<p><%= link_to "Edit", edit_recipe_path(@recipe) %></p>
<p><%= link_to "Delete", recipe_path(@recipe), :data =>
  {
    :confirm => "You sure?",
    :method => "delete"
  } %></p>

<p><%= link_to "Return to recipes", recipes_path %></p>